[package]
name = "basic-cog"
version.workspace = true
edition.workspace = true

[dependencies]
gearbox-rs-core = { path = "../../core" }
gearbox-rs-macros = { path = "../../macros" }
tokio = { workspace = true, features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = "0.3"
dashmap = { workspace = true }
uuid = { version = "1.0", features = ["v4"] }
axum = { workspace = true }
