//! Attribute parsing for the Crud derive macro.

use syn::{Attribute, Data, DeriveInput, Fields, Ident, Meta, MetaList, Type};

/// Operators that can be used for filtering on searchable fields.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SearchOperator {
    /// Exact match (=)
    Eq,
    /// ILIKE pattern match
    Like,
    /// ILIKE prefix match (value%)
    StartsWith,
    /// Greater than (>)
    Gt,
    /// Greater than or equal (>=)
    Gte,
    /// Less than (<)
    Lt,
    /// Less than or equal (<=)
    Lte,
}

impl SearchOperator {
    /// Get the suffix for this operator in query params.
    pub fn suffix(&self) -> &'static str {
        match self {
            SearchOperator::Eq => "",
            SearchOperator::Like => "_like",
            SearchOperator::StartsWith => "_starts_with",
            SearchOperator::Gt => "_gt",
            SearchOperator::Gte => "_gte",
            SearchOperator::Lt => "_lt",
            SearchOperator::Lte => "_lte",
        }
    }

    /// Get the SQL operator for this search operator.
    pub fn sql_operator(&self) -> &'static str {
        match self {
            SearchOperator::Eq => "=",
            SearchOperator::Like => "ILIKE",
            SearchOperator::StartsWith => "ILIKE",
            SearchOperator::Gt => ">",
            SearchOperator::Gte => ">=",
            SearchOperator::Lt => "<",
            SearchOperator::Lte => "<=",
        }
    }

    /// Whether this operator requires value transformation (e.g., adding %).
    #[allow(dead_code)]
    pub fn transform_value(&self) -> Option<&'static str> {
        match self {
            SearchOperator::Like => Some("'%' || {} || '%'"),
            SearchOperator::StartsWith => Some("{} || '%'"),
            _ => None,
        }
    }
}

/// Information about a searchable field's operators.
#[derive(Debug, Clone)]
pub struct SearchableInfo {
    pub operators: Vec<SearchOperator>,
}

impl SearchableInfo {
    /// Get default operators based on field type.
    pub fn default_for_type(ty: &Type) -> Self {
        let type_str = quote::quote!(#ty).to_string();
        let operators = match type_str.as_str() {
            "String" | "& str" | "std :: string :: String" => {
                vec![SearchOperator::Eq, SearchOperator::Like, SearchOperator::StartsWith]
            }
            "i32" | "i64" | "i16" | "i8" | "u32" | "u64" | "u16" | "u8" | "f32" | "f64" => {
                vec![
                    SearchOperator::Eq,
                    SearchOperator::Gt,
                    SearchOperator::Gte,
                    SearchOperator::Lt,
                    SearchOperator::Lte,
                ]
            }
            s if s.contains("DateTime") || s.contains("NaiveDate") || s.contains("NaiveDateTime") => {
                vec![
                    SearchOperator::Eq,
                    SearchOperator::Gt,
                    SearchOperator::Gte,
                    SearchOperator::Lt,
                    SearchOperator::Lte,
                ]
            }
            "bool" => vec![SearchOperator::Eq],
            s if s.contains("Uuid") => vec![SearchOperator::Eq],
            _ => vec![SearchOperator::Eq],
        };
        SearchableInfo { operators }
    }

    /// Parse operators from attribute arguments like `#[searchable(eq, like)]`.
    pub fn from_operators(ops: &[&str]) -> Self {
        let operators = ops
            .iter()
            .filter_map(|op| match *op {
                "eq" => Some(SearchOperator::Eq),
                "like" => Some(SearchOperator::Like),
                "starts_with" => Some(SearchOperator::StartsWith),
                "gt" => Some(SearchOperator::Gt),
                "gte" => Some(SearchOperator::Gte),
                "lt" => Some(SearchOperator::Lt),
                "lte" => Some(SearchOperator::Lte),
                _ => None,
            })
            .collect();
        SearchableInfo { operators }
    }
}

/// Information about a single field in the entity.
#[derive(Debug, Clone)]
pub struct CrudFieldInfo {
    pub ident: Ident,
    pub ty: Type,
    /// Field is a primary key.
    pub is_primary_key: bool,
    /// Field is auto-generated by the database (UUID, serial, etc.).
    pub auto_generated: bool,
    /// Field is read-only (only in responses, not in create/update).
    pub readonly: bool,
    /// Field is write-only (only in create/update, not in responses).
    pub writeonly: bool,
    /// Field should be skipped entirely from CRUD operations.
    pub skip: bool,
    /// Field is searchable with specific operators.
    pub searchable: Option<SearchableInfo>,
    /// Optional pg_type override for SQL binding.
    #[allow(dead_code)]
    pub pg_type: Option<Type>,
}

impl CrudFieldInfo {
    /// Check if field should be included in Create DTO.
    pub fn include_in_create(&self) -> bool {
        !self.auto_generated && !self.readonly && !self.skip
    }

    /// Check if field should be included in Update DTO.
    pub fn include_in_update(&self) -> bool {
        !self.auto_generated && !self.readonly && !self.skip && !self.is_primary_key
    }

    /// Check if field should be included in Response DTO.
    pub fn include_in_response(&self) -> bool {
        !self.writeonly && !self.skip
    }
}

/// Struct-level CRUD configuration.
#[derive(Debug, Clone)]
pub struct CrudConfig {
    /// Base path for REST endpoints (e.g., "/users").
    pub path: String,
    /// Whether this entity is read-only (no mutation endpoints).
    pub read_only: bool,
    /// Skip POST endpoint.
    pub skip_create: bool,
    /// Skip DELETE endpoint.
    pub skip_delete: bool,
}

impl Default for CrudConfig {
    fn default() -> Self {
        CrudConfig {
            path: String::new(),
            read_only: false,
            skip_create: false,
            skip_delete: false,
        }
    }
}

/// Parsed entity information for CRUD generation.
#[derive(Debug)]
pub struct CrudEntityInfo {
    pub name: Ident,
    pub table: String,
    pub config: CrudConfig,
    pub fields: Vec<CrudFieldInfo>,
}

impl CrudEntityInfo {
    /// Get primary key fields.
    pub fn pk_fields(&self) -> Vec<&CrudFieldInfo> {
        self.fields.iter().filter(|f| f.is_primary_key).collect()
    }

    /// Get database fields (not skipped).
    pub fn db_fields(&self) -> Vec<&CrudFieldInfo> {
        self.fields.iter().filter(|f| !f.skip).collect()
    }

    /// Get fields for Create DTO.
    pub fn create_fields(&self) -> Vec<&CrudFieldInfo> {
        self.fields.iter().filter(|f| f.include_in_create()).collect()
    }

    /// Get fields for Update DTO.
    pub fn update_fields(&self) -> Vec<&CrudFieldInfo> {
        self.fields.iter().filter(|f| f.include_in_update()).collect()
    }

    /// Get fields for Response DTO.
    pub fn response_fields(&self) -> Vec<&CrudFieldInfo> {
        self.fields.iter().filter(|f| f.include_in_response()).collect()
    }

    /// Get searchable fields.
    pub fn searchable_fields(&self) -> Vec<&CrudFieldInfo> {
        self.fields
            .iter()
            .filter(|f| f.searchable.is_some() && !f.skip)
            .collect()
    }

    /// Get the entity name in snake_case for function naming.
    pub fn snake_case_name(&self) -> String {
        to_snake_case(&self.name.to_string())
    }

    /// Get default path if not specified.
    pub fn default_path(&self) -> String {
        format!("/{}", pluralize(&self.snake_case_name()))
    }

    /// Get the effective path (specified or default).
    pub fn effective_path(&self) -> String {
        if self.config.path.is_empty() {
            self.default_path()
        } else {
            self.config.path.clone()
        }
    }
}

/// Parse the #[crud(...)] attribute from a struct.
fn parse_crud_config(attrs: &[Attribute]) -> CrudConfig {
    let mut config = CrudConfig::default();

    for attr in attrs {
        if !attr.path().is_ident("crud") {
            continue;
        }

        if let Meta::List(MetaList { tokens, .. }) = &attr.meta {
            let tokens_str = tokens.to_string();
            for part in tokens_str.split(',') {
                let part = part.trim();
                if part.starts_with("path") {
                    if let Some(value) = extract_string_value(part) {
                        config.path = value;
                    }
                } else if part == "read_only" {
                    config.read_only = true;
                } else if part == "skip_create" {
                    config.skip_create = true;
                } else if part == "skip_delete" {
                    config.skip_delete = true;
                }
            }
        }
    }

    config
}

/// Extract a string value from an attribute part like `path = "/users"`.
fn extract_string_value(part: &str) -> Option<String> {
    let parts: Vec<&str> = part.splitn(2, '=').collect();
    if parts.len() == 2 {
        let value = parts[1].trim();
        // Remove quotes
        if value.starts_with('"') && value.ends_with('"') {
            return Some(value[1..value.len() - 1].to_string());
        }
    }
    None
}

/// Parse the #[table("name")] attribute.
fn parse_table_name(attrs: &[Attribute]) -> Option<String> {
    for attr in attrs {
        if attr.path().is_ident("table") {
            if let Ok(lit) = attr.parse_args::<syn::LitStr>() {
                return Some(lit.value());
            }
        }
    }
    None
}

/// Parse searchable attribute, optionally with explicit operators.
fn parse_searchable(attr: &Attribute, field_ty: &Type) -> Option<SearchableInfo> {
    if !attr.path().is_ident("searchable") {
        return None;
    }

    // Check if it has arguments
    match &attr.meta {
        Meta::Path(_) => {
            // No arguments, use default operators for type
            Some(SearchableInfo::default_for_type(field_ty))
        }
        Meta::List(MetaList { tokens, .. }) => {
            // Has arguments like `#[searchable(eq, like)]`
            let tokens_str = tokens.to_string();
            let ops: Vec<&str> = tokens_str.split(',').map(|s| s.trim()).collect();
            Some(SearchableInfo::from_operators(&ops))
        }
        _ => Some(SearchableInfo::default_for_type(field_ty)),
    }
}

/// Parse a single field's attributes.
fn parse_field_info(field: &syn::Field) -> CrudFieldInfo {
    let ident = field.ident.clone().expect("Named field required");
    let ty = field.ty.clone();

    let mut is_primary_key = false;
    let mut auto_generated = false;
    let mut readonly = false;
    let mut writeonly = false;
    let mut skip = false;
    let mut searchable = None;
    let mut pg_type = None;

    for attr in &field.attrs {
        if attr.path().is_ident("primary_key") {
            is_primary_key = true;
        } else if attr.path().is_ident("auto_generated") {
            auto_generated = true;
        } else if attr.path().is_ident("readonly") {
            readonly = true;
        } else if attr.path().is_ident("writeonly") {
            writeonly = true;
        } else if attr.path().is_ident("skip") {
            skip = true;
        } else if attr.path().is_ident("searchable") {
            searchable = parse_searchable(attr, &ty);
        } else if attr.path().is_ident("pg_type") {
            pg_type = attr.parse_args::<Type>().ok();
        }
    }

    CrudFieldInfo {
        ident,
        ty,
        is_primary_key,
        auto_generated,
        readonly,
        writeonly,
        skip,
        searchable,
        pg_type,
    }
}

/// Parse the entire entity from DeriveInput.
pub fn parse_crud_entity(input: &DeriveInput) -> CrudEntityInfo {
    let name = input.ident.clone();

    // Parse table name (required - comes from PgEntity)
    let table = parse_table_name(&input.attrs)
        .expect("#[table(\"name\")] attribute is required for Crud derive");

    // Parse crud config
    let config = parse_crud_config(&input.attrs);

    // Parse fields
    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(fields) => fields.named.iter().map(parse_field_info).collect(),
            _ => panic!("Crud can only be derived for structs with named fields"),
        },
        _ => panic!("Crud can only be derived for structs"),
    };

    CrudEntityInfo {
        name,
        table,
        config,
        fields,
    }
}

/// Convert PascalCase to snake_case.
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

/// Simple pluralization for entity names.
fn pluralize(s: &str) -> String {
    if s.ends_with('s') || s.ends_with('x') || s.ends_with("ch") || s.ends_with("sh") {
        format!("{}es", s)
    } else if s.ends_with('y') && !s.ends_with("ey") && !s.ends_with("ay") && !s.ends_with("oy") && !s.ends_with("uy") {
        format!("{}ies", &s[..s.len() - 1])
    } else {
        format!("{}s", s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("User"), "user");
        assert_eq!(to_snake_case("UserProfile"), "user_profile");
        assert_eq!(to_snake_case("HTMLParser"), "h_t_m_l_parser");
    }

    #[test]
    fn test_pluralize() {
        assert_eq!(pluralize("user"), "users");
        assert_eq!(pluralize("category"), "categories");
        assert_eq!(pluralize("box"), "boxes");
        assert_eq!(pluralize("key"), "keys");
    }

    #[test]
    fn test_search_operator_suffix() {
        assert_eq!(SearchOperator::Eq.suffix(), "");
        assert_eq!(SearchOperator::Like.suffix(), "_like");
        assert_eq!(SearchOperator::Gte.suffix(), "_gte");
    }
}
