[workspace]
resolver = "3"
members = [
    "gearbox",
    "core",
    "pg",
    "macros",
    "examples/*",
    "integration-tests"
]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/Empire-Pixelworks/gearbox-rs"
keywords = ["web", "framework", "dependency-injection", "axum", "async"]
categories = ["web-programming::http-server", "asynchronous"]
authors = ["Brandon Lanthrip <blanthrip@gmail.com>"]

[workspace.dependencies]
tokio = { version = "1", features = ["signal", "time"] }
async-trait = "0.1"
dashmap = "6.1"
thiserror = "2.0"
tracing = "0.1"
axum = "0.8"
inventory = "0.3"
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"