[package]
name = "gearbox-rs-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true
description = "PostgreSQL integration for Gearbox framework"
readme = "../README.md"

[dependencies]
gearbox-rs-core = { path = "../core", version = "0.2.0" }
gearbox-rs-macros = { path = "../macros", version = "0.2.0" }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"]}
thiserror = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
async-trait = { workspace = true }