[package]
name = "postgres-example"
version.workspace = true
edition.workspace = true

[dependencies]
gearbox-rs-core = { path = "../../core" }
gearbox-rs-macros = { path = "../../macros" }
gearbox-rs-postgres = { path = "../../pg" }
tokio = { workspace = true, features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = "0.3"
dashmap = { workspace = true }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
axum = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres"] }
serde_json = "1.0"