[gearbox_app]
http-port = 8090

[postgres]

[postgres.schemas.users]
schema_name = "users_schema"
migration_path = "./migrations/users"

[postgres.schemas.posts]
schema_name = "posts_schema"
migration_path = "./migrations/posts"
