//! CRUD query builder implementation for PgClient.

use async_trait::async_trait;

use crate::{PgEntity, PgError};
use gearbox_rs_core::crud::BuildWhereClause;

/// Trait for executing filtered queries against the database.
///
/// This trait extends the basic repository operations with dynamic
/// filtering capabilities based on query DTOs generated by the Crud macro.
#[async_trait]
pub trait QueryBuilder<T: PgEntity, Q: BuildWhereClause + Send + Sync>: Send + Sync {
    /// Execute a filtered query and return matching entities.
    async fn query_filtered(&self, query: &Q) -> Result<Vec<T>, PgError>;

    /// Count entities matching the filter criteria.
    async fn count_filtered(&self, query: &Q) -> Result<i64, PgError>;
}
