[package]
name = "gearbox-macros"
version.workspace = true
edition.workspace = true
authors = ["Brandon Lanthrip <blanthrip@gmail.com>"]
description = "Procedural macros for Gearbox framework"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
gearbox-core = { path = "../core" }
gearbox-postgres = { path = "../pg" }
serde = { version = "1.0", features = ["derive"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
axum = { workspace = true }
inventory = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres"] }
